# Arduino Make file. Refer to https://github.com/sudar/Arduino-Makefile




BOARD_TAG   = nano
BOARD_SUB   = atmega328old
ARDUINO_DIR = /usr/local/arduino
include /usr/local/Arduino-Makefile/Arduino.mk


